// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2026, 10:24:31 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/GOLANG/QuickWork/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/plugins/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/composables/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/utils/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"fontFamily":{"sans":["\"Segoe UI\"","\"Inter\"","\"Be Vietnam Pro\"","\"Noto Sans\"","Arial","sans-serif"]}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;