// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/29/2026, 10:58:27 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/GOLANG/QuickWork/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/plugins/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/composables/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/utils/**/*.{js,ts,mjs}","D:/GOLANG/QuickWork/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/GOLANG/QuickWork/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;