
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppFooter: typeof import("../app/components/AppFooter.vue")['default']
export const AppFooterVue: typeof import("../app/components/AppFooter.vue")['default']
export const AppHeader: typeof import("../app/components/AppHeader.vue")['default']
export const AppHeaderVue: typeof import("../app/components/AppHeader.vue")['default']
export const AppSidebar: typeof import("../app/components/AppSidebar.vue")['default']
export const AppSidebarVue: typeof import("../app/components/AppSidebar.vue")['default']
export const AuthBrandMark: typeof import("../app/components/AuthBrandMark.vue")['default']
export const AuthBrandMarkVue: typeof import("../app/components/AuthBrandMark.vue")['default']
export const AuthField: typeof import("../app/components/AuthField.vue")['default']
export const AuthFieldVue: typeof import("../app/components/AuthField.vue")['default']
export const AuthLoginExperience: typeof import("../app/components/AuthLoginExperience.vue")['default']
export const AuthLoginExperienceVue: typeof import("../app/components/AuthLoginExperience.vue")['default']
export const AuthRegisterExperience: typeof import("../app/components/AuthRegisterExperience.vue")['default']
export const AuthRegisterExperienceVue: typeof import("../app/components/AuthRegisterExperience.vue")['default']
export const AuthShell: typeof import("../app/components/AuthShell.vue")['default']
export const AuthShellVue: typeof import("../app/components/AuthShell.vue")['default']
export const ConfirmDialog: typeof import("../app/components/ConfirmDialog.vue")['default']
export const ConfirmDialogVue: typeof import("../app/components/ConfirmDialog.vue")['default']
export const EmptyState: typeof import("../app/components/EmptyState.vue")['default']
export const EmptyStateVue: typeof import("../app/components/EmptyState.vue")['default']
export const FooterBrandMark: typeof import("../app/components/FooterBrandMark.vue")['default']
export const FooterBrandMarkVue: typeof import("../app/components/FooterBrandMark.vue")['default']
export const FormActions: typeof import("../app/components/FormActions.vue")['default']
export const FormActionsVue: typeof import("../app/components/FormActions.vue")['default']
export const HomeCategoryCard: typeof import("../app/components/HomeCategoryCard.vue")['default']
export const HomeCategoryCardVue: typeof import("../app/components/HomeCategoryCard.vue")['default']
export const HomeJobCard: typeof import("../app/components/HomeJobCard.vue")['default']
export const HomeJobCardVue: typeof import("../app/components/HomeJobCard.vue")['default']
export const HomeLandingPage: typeof import("../app/components/HomeLandingPage.vue")['default']
export const HomeLandingPageVue: typeof import("../app/components/HomeLandingPage.vue")['default']
export const JobMatchScoreBadge: typeof import("../app/components/JobMatchScoreBadge.vue")['default']
export const LoadingSpinner: typeof import("../app/components/LoadingSpinner.vue")['default']
export const LoadingSpinnerVue: typeof import("../app/components/LoadingSpinner.vue")['default']
export const Pagination: typeof import("../app/components/Pagination.vue")['default']
export const PaginationVue: typeof import("../app/components/Pagination.vue")['default']
export const PasswordField: typeof import("../app/components/PasswordField.vue")['default']
export const PasswordFieldVue: typeof import("../app/components/PasswordField.vue")['default']
export const SearchBox: typeof import("../app/components/SearchBox.vue")['default']
export const SearchBoxVue: typeof import("../app/components/SearchBox.vue")['default']
export const SectionHeading: typeof import("../app/components/SectionHeading.vue")['default']
export const SectionHeadingVue: typeof import("../app/components/SectionHeading.vue")['default']
export const StudentSettingsWorkspace: typeof import("../app/components/StudentSettingsWorkspace.vue")['default']
export const StudentSettingsWorkspaceVue: typeof import("../app/components/StudentSettingsWorkspace.vue")['default']
export const ToggleSetting: typeof import("../app/components/ToggleSetting.vue")['default']
export const ToggleSettingVue: typeof import("../app/components/ToggleSetting.vue")['default']
export const AdminTablePagination: typeof import("../app/components/admin/AdminTablePagination.vue")['default']
export const AdminTablePaginationVue: typeof import("../app/components/admin/AdminTablePagination.vue")['default']
export const EnterpriseCandidateCollectionView: typeof import("../app/components/enterprise/CandidateCollectionView.vue")['default']
export const EnterpriseCandidateCollectionViewVue: typeof import("../app/components/enterprise/CandidateCollectionView.vue")['default']
export const EnterpriseCompanyProfileSettings: typeof import("../app/components/enterprise/EnterpriseCompanyProfileSettings.vue")['default']
export const EnterpriseFileUploadField: typeof import("../app/components/enterprise/EnterpriseFileUploadField.vue")['default']
export const EnterpriseLocationMap: typeof import("../app/components/enterprise/EnterpriseLocationMap.vue")['default']
export const EnterpriseMessageCenter: typeof import("../app/components/enterprise/EnterpriseMessageCenter.vue")['default']
export const EnterpriseMessageCenterVue: typeof import("../app/components/enterprise/EnterpriseMessageCenter.vue")['default']
export const HomeCareerToolsDropdown: typeof import("../app/components/home/CareerToolsDropdown.vue")['default']
export const HomeCompanyLogo: typeof import("../app/components/home/CompanyLogo.vue")['default']
export const HomeCareerAI: typeof import("../app/components/home/HomeCareerAI.vue")['default']
export const HomeCareerCta: typeof import("../app/components/home/HomeCareerCta.vue")['default']
export const HomeCareerCtaVue: typeof import("../app/components/home/HomeCareerCta.vue")['default']
export const HomeCategories: typeof import("../app/components/home/HomeCategories.vue")['default']
export const HomeCategoriesVue: typeof import("../app/components/home/HomeCategories.vue")['default']
export const HomeEmployerCta: typeof import("../app/components/home/HomeEmployerCta.vue")['default']
export const HomeEmployerCtaVue: typeof import("../app/components/home/HomeEmployerCta.vue")['default']
export const HomeFeaturedJobs: typeof import("../app/components/home/HomeFeaturedJobs.vue")['default']
export const HomeFeaturedJobsVue: typeof import("../app/components/home/HomeFeaturedJobs.vue")['default']
export const HomeFooter: typeof import("../app/components/home/HomeFooter.vue")['default']
export const HomeFooterVue: typeof import("../app/components/home/HomeFooter.vue")['default']
export const HomeHeader: typeof import("../app/components/home/HomeHeader.vue")['default']
export const HomeHeaderVue: typeof import("../app/components/home/HomeHeader.vue")['default']
export const HomeHero: typeof import("../app/components/home/HomeHero.vue")['default']
export const HomeHeroVue: typeof import("../app/components/home/HomeHero.vue")['default']
export const HomeJobDetailPanel: typeof import("../app/components/home/HomeJobDetailPanel.vue")['default']
export const HomeJobDetailPanelVue: typeof import("../app/components/home/HomeJobDetailPanel.vue")['default']
export const HomeQuickStats: typeof import("../app/components/home/HomeQuickStats.vue")['default']
export const HomeQuickStatsVue: typeof import("../app/components/home/HomeQuickStats.vue")['default']
export const HomeSearchBar: typeof import("../app/components/home/HomeSearchBar.vue")['default']
export const HomeSearchBarVue: typeof import("../app/components/home/HomeSearchBar.vue")['default']
export const StudentProfileWorkspace: typeof import("../app/components/student/StudentProfileWorkspace.vue")['default']
export const UiButton: typeof import("../app/components/ui/Button.vue")['default']
export const UiButtonVue: typeof import("../app/components/ui/Button.vue")['default']
export const UiInput: typeof import("../app/components/ui/Input.vue")['default']
export const UiInputVue: typeof import("../app/components/ui/Input.vue")['default']
export const UiModal: typeof import("../app/components/ui/Modal.vue")['default']
export const UiModalVue: typeof import("../app/components/ui/Modal.vue")['default']
export const UiNotificationDropdown: typeof import("../app/components/ui/NotificationDropdown.vue")['default']
export const UiNotificationDropdownVue: typeof import("../app/components/ui/NotificationDropdown.vue")['default']
export const UiScrollSelect: typeof import("../app/components/ui/ScrollSelect.vue")['default']
export const UiScrollSelectVue: typeof import("../app/components/ui/ScrollSelect.vue")['default']
export const UiSelect: typeof import("../app/components/ui/Select.vue")['default']
export const UiSelectVue: typeof import("../app/components/ui/Select.vue")['default']
export const UiSkeleton: typeof import("../app/components/ui/Skeleton.vue")['default']
export const UiSkeletonVue: typeof import("../app/components/ui/Skeleton.vue")['default']
export const UiTextarea: typeof import("../app/components/ui/Textarea.vue")['default']
export const UiTextareaVue: typeof import("../app/components/ui/Textarea.vue")['default']
export const UiToast: typeof import("../app/components/ui/Toast.vue")['default']
export const UiToastVue: typeof import("../app/components/ui/Toast.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppFooter: LazyComponent<typeof import("../app/components/AppFooter.vue")['default']>
export const LazyAppFooterVue: LazyComponent<typeof import("../app/components/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/AppHeader.vue")['default']>
export const LazyAppHeaderVue: LazyComponent<typeof import("../app/components/AppHeader.vue")['default']>
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/AppSidebar.vue")['default']>
export const LazyAppSidebarVue: LazyComponent<typeof import("../app/components/AppSidebar.vue")['default']>
export const LazyAuthBrandMark: LazyComponent<typeof import("../app/components/AuthBrandMark.vue")['default']>
export const LazyAuthBrandMarkVue: LazyComponent<typeof import("../app/components/AuthBrandMark.vue")['default']>
export const LazyAuthField: LazyComponent<typeof import("../app/components/AuthField.vue")['default']>
export const LazyAuthFieldVue: LazyComponent<typeof import("../app/components/AuthField.vue")['default']>
export const LazyAuthLoginExperience: LazyComponent<typeof import("../app/components/AuthLoginExperience.vue")['default']>
export const LazyAuthLoginExperienceVue: LazyComponent<typeof import("../app/components/AuthLoginExperience.vue")['default']>
export const LazyAuthRegisterExperience: LazyComponent<typeof import("../app/components/AuthRegisterExperience.vue")['default']>
export const LazyAuthRegisterExperienceVue: LazyComponent<typeof import("../app/components/AuthRegisterExperience.vue")['default']>
export const LazyAuthShell: LazyComponent<typeof import("../app/components/AuthShell.vue")['default']>
export const LazyAuthShellVue: LazyComponent<typeof import("../app/components/AuthShell.vue")['default']>
export const LazyConfirmDialog: LazyComponent<typeof import("../app/components/ConfirmDialog.vue")['default']>
export const LazyConfirmDialogVue: LazyComponent<typeof import("../app/components/ConfirmDialog.vue")['default']>
export const LazyEmptyState: LazyComponent<typeof import("../app/components/EmptyState.vue")['default']>
export const LazyEmptyStateVue: LazyComponent<typeof import("../app/components/EmptyState.vue")['default']>
export const LazyFooterBrandMark: LazyComponent<typeof import("../app/components/FooterBrandMark.vue")['default']>
export const LazyFooterBrandMarkVue: LazyComponent<typeof import("../app/components/FooterBrandMark.vue")['default']>
export const LazyFormActions: LazyComponent<typeof import("../app/components/FormActions.vue")['default']>
export const LazyFormActionsVue: LazyComponent<typeof import("../app/components/FormActions.vue")['default']>
export const LazyHomeCategoryCard: LazyComponent<typeof import("../app/components/HomeCategoryCard.vue")['default']>
export const LazyHomeCategoryCardVue: LazyComponent<typeof import("../app/components/HomeCategoryCard.vue")['default']>
export const LazyHomeJobCard: LazyComponent<typeof import("../app/components/HomeJobCard.vue")['default']>
export const LazyHomeJobCardVue: LazyComponent<typeof import("../app/components/HomeJobCard.vue")['default']>
export const LazyHomeLandingPage: LazyComponent<typeof import("../app/components/HomeLandingPage.vue")['default']>
export const LazyHomeLandingPageVue: LazyComponent<typeof import("../app/components/HomeLandingPage.vue")['default']>
export const LazyJobMatchScoreBadge: LazyComponent<typeof import("../app/components/JobMatchScoreBadge.vue")['default']>
export const LazyLoadingSpinner: LazyComponent<typeof import("../app/components/LoadingSpinner.vue")['default']>
export const LazyLoadingSpinnerVue: LazyComponent<typeof import("../app/components/LoadingSpinner.vue")['default']>
export const LazyPagination: LazyComponent<typeof import("../app/components/Pagination.vue")['default']>
export const LazyPaginationVue: LazyComponent<typeof import("../app/components/Pagination.vue")['default']>
export const LazyPasswordField: LazyComponent<typeof import("../app/components/PasswordField.vue")['default']>
export const LazyPasswordFieldVue: LazyComponent<typeof import("../app/components/PasswordField.vue")['default']>
export const LazySearchBox: LazyComponent<typeof import("../app/components/SearchBox.vue")['default']>
export const LazySearchBoxVue: LazyComponent<typeof import("../app/components/SearchBox.vue")['default']>
export const LazySectionHeading: LazyComponent<typeof import("../app/components/SectionHeading.vue")['default']>
export const LazySectionHeadingVue: LazyComponent<typeof import("../app/components/SectionHeading.vue")['default']>
export const LazyStudentSettingsWorkspace: LazyComponent<typeof import("../app/components/StudentSettingsWorkspace.vue")['default']>
export const LazyStudentSettingsWorkspaceVue: LazyComponent<typeof import("../app/components/StudentSettingsWorkspace.vue")['default']>
export const LazyToggleSetting: LazyComponent<typeof import("../app/components/ToggleSetting.vue")['default']>
export const LazyToggleSettingVue: LazyComponent<typeof import("../app/components/ToggleSetting.vue")['default']>
export const LazyAdminTablePagination: LazyComponent<typeof import("../app/components/admin/AdminTablePagination.vue")['default']>
export const LazyAdminTablePaginationVue: LazyComponent<typeof import("../app/components/admin/AdminTablePagination.vue")['default']>
export const LazyEnterpriseCandidateCollectionView: LazyComponent<typeof import("../app/components/enterprise/CandidateCollectionView.vue")['default']>
export const LazyEnterpriseCandidateCollectionViewVue: LazyComponent<typeof import("../app/components/enterprise/CandidateCollectionView.vue")['default']>
export const LazyEnterpriseCompanyProfileSettings: LazyComponent<typeof import("../app/components/enterprise/EnterpriseCompanyProfileSettings.vue")['default']>
export const LazyEnterpriseFileUploadField: LazyComponent<typeof import("../app/components/enterprise/EnterpriseFileUploadField.vue")['default']>
export const LazyEnterpriseLocationMap: LazyComponent<typeof import("../app/components/enterprise/EnterpriseLocationMap.vue")['default']>
export const LazyEnterpriseMessageCenter: LazyComponent<typeof import("../app/components/enterprise/EnterpriseMessageCenter.vue")['default']>
export const LazyEnterpriseMessageCenterVue: LazyComponent<typeof import("../app/components/enterprise/EnterpriseMessageCenter.vue")['default']>
export const LazyHomeCareerToolsDropdown: LazyComponent<typeof import("../app/components/home/CareerToolsDropdown.vue")['default']>
export const LazyHomeCompanyLogo: LazyComponent<typeof import("../app/components/home/CompanyLogo.vue")['default']>
export const LazyHomeCareerAI: LazyComponent<typeof import("../app/components/home/HomeCareerAI.vue")['default']>
export const LazyHomeCareerCta: LazyComponent<typeof import("../app/components/home/HomeCareerCta.vue")['default']>
export const LazyHomeCareerCtaVue: LazyComponent<typeof import("../app/components/home/HomeCareerCta.vue")['default']>
export const LazyHomeCategories: LazyComponent<typeof import("../app/components/home/HomeCategories.vue")['default']>
export const LazyHomeCategoriesVue: LazyComponent<typeof import("../app/components/home/HomeCategories.vue")['default']>
export const LazyHomeEmployerCta: LazyComponent<typeof import("../app/components/home/HomeEmployerCta.vue")['default']>
export const LazyHomeEmployerCtaVue: LazyComponent<typeof import("../app/components/home/HomeEmployerCta.vue")['default']>
export const LazyHomeFeaturedJobs: LazyComponent<typeof import("../app/components/home/HomeFeaturedJobs.vue")['default']>
export const LazyHomeFeaturedJobsVue: LazyComponent<typeof import("../app/components/home/HomeFeaturedJobs.vue")['default']>
export const LazyHomeFooter: LazyComponent<typeof import("../app/components/home/HomeFooter.vue")['default']>
export const LazyHomeFooterVue: LazyComponent<typeof import("../app/components/home/HomeFooter.vue")['default']>
export const LazyHomeHeader: LazyComponent<typeof import("../app/components/home/HomeHeader.vue")['default']>
export const LazyHomeHeaderVue: LazyComponent<typeof import("../app/components/home/HomeHeader.vue")['default']>
export const LazyHomeHero: LazyComponent<typeof import("../app/components/home/HomeHero.vue")['default']>
export const LazyHomeHeroVue: LazyComponent<typeof import("../app/components/home/HomeHero.vue")['default']>
export const LazyHomeJobDetailPanel: LazyComponent<typeof import("../app/components/home/HomeJobDetailPanel.vue")['default']>
export const LazyHomeJobDetailPanelVue: LazyComponent<typeof import("../app/components/home/HomeJobDetailPanel.vue")['default']>
export const LazyHomeQuickStats: LazyComponent<typeof import("../app/components/home/HomeQuickStats.vue")['default']>
export const LazyHomeQuickStatsVue: LazyComponent<typeof import("../app/components/home/HomeQuickStats.vue")['default']>
export const LazyHomeSearchBar: LazyComponent<typeof import("../app/components/home/HomeSearchBar.vue")['default']>
export const LazyHomeSearchBarVue: LazyComponent<typeof import("../app/components/home/HomeSearchBar.vue")['default']>
export const LazyStudentProfileWorkspace: LazyComponent<typeof import("../app/components/student/StudentProfileWorkspace.vue")['default']>
export const LazyUiButton: LazyComponent<typeof import("../app/components/ui/Button.vue")['default']>
export const LazyUiButtonVue: LazyComponent<typeof import("../app/components/ui/Button.vue")['default']>
export const LazyUiInput: LazyComponent<typeof import("../app/components/ui/Input.vue")['default']>
export const LazyUiInputVue: LazyComponent<typeof import("../app/components/ui/Input.vue")['default']>
export const LazyUiModal: LazyComponent<typeof import("../app/components/ui/Modal.vue")['default']>
export const LazyUiModalVue: LazyComponent<typeof import("../app/components/ui/Modal.vue")['default']>
export const LazyUiNotificationDropdown: LazyComponent<typeof import("../app/components/ui/NotificationDropdown.vue")['default']>
export const LazyUiNotificationDropdownVue: LazyComponent<typeof import("../app/components/ui/NotificationDropdown.vue")['default']>
export const LazyUiScrollSelect: LazyComponent<typeof import("../app/components/ui/ScrollSelect.vue")['default']>
export const LazyUiScrollSelectVue: LazyComponent<typeof import("../app/components/ui/ScrollSelect.vue")['default']>
export const LazyUiSelect: LazyComponent<typeof import("../app/components/ui/Select.vue")['default']>
export const LazyUiSelectVue: LazyComponent<typeof import("../app/components/ui/Select.vue")['default']>
export const LazyUiSkeleton: LazyComponent<typeof import("../app/components/ui/Skeleton.vue")['default']>
export const LazyUiSkeletonVue: LazyComponent<typeof import("../app/components/ui/Skeleton.vue")['default']>
export const LazyUiTextarea: LazyComponent<typeof import("../app/components/ui/Textarea.vue")['default']>
export const LazyUiTextareaVue: LazyComponent<typeof import("../app/components/ui/Textarea.vue")['default']>
export const LazyUiToast: LazyComponent<typeof import("../app/components/ui/Toast.vue")['default']>
export const LazyUiToastVue: LazyComponent<typeof import("../app/components/ui/Toast.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
